# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - taa-portal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
#       - name: Lint
#         uses: ricardochaves/python-lint@v1.4.0
#         with:
#           use-flake8: true
#           extra-flake8-options: "--ignore=E201,E202,E501,F403,F405"
      
      - name: Perform spell check
        uses: sobolevn/misspell-fixer-action@0.1.0
        
      - name: Create a PR for any issues that are identified
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Fixes by misspell-fixer'
          title: 'Typos fix by misspell-fixer'

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: python -m venv venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt

#       - name: Create and start virtual environment
#         run: |
#           python -m venv venv
#           source venv/bin/activate
      
#       - name: Install dependencies
#         run: pip install -r requirements.txt
        
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.SP_CREDENTIALS }}
          
      - name: Run tests
        run: python manage.py test
        env:
          "Django__KeyVaultName": ${{ secrets.KEYVAULT_NAME }}
          "APPLICATIONINSIGHTS_CONNECTION_STRING": ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
          
      - name: Calculate code coverage
        run: |
            coverage run --source="." --omit="adoptionsite/migrations*" manage.py test adoptionsite
            coverage report
        env:
            "Django__KeyVaultName": ${{ secrets.KEYVAULT_NAME }}
            "APPLICATIONINSIGHTS_CONNECTION_STRING": ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
        
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
            
      - name: Upload a build artifact for the Bicep template
        uses: actions/upload-artifact@v2.1.3
        with:
          name: bicep-template
          path: template.bicep
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-1.outputs.webapp-url }}
#       url: "http://travis-oss-on-azure.azurefd.net"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: Download the bicep-template artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: bicep-template
          path: ./bicep-template/
          
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.SP_CREDENTIALS}}
          
      - name: 'Deploy to Azure Web App 1'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp-1
        with:
          app-name: 'taa-portal'
          slot-name: 'Production'
          
      - name: 'Deploy to Azure Web App 2'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp-2
        with:
          app-name: 'taa-portal2'
          slot-name: 'Production'

      - name: Azure Setup Settings 1
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'taa-portal'
          app-settings-json: '[{"name": "Django__KeyVaultName","value": "${{secrets.KEYVAULT_NAME }}","slotSetting": false},{"name": "Django__Debug","value": "True","slotSetting": false},{"name": "APPLICATIONINSIGHTS_CONNECTION_STRING","value": "${{secrets.REDIS_CONNECTION_STRING}}","slotSetting": false}]'

      - name: Azure Setup Settings 2
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'taa-portal2'
          app-settings-json: '[{"name": "Django__KeyVaultName","value": "${{secrets.KEYVAULT_NAME }}","slotSetting": false},{"name": "Django__Debug","value": "True","slotSetting": false},{"name": "APPLICATIONINSIGHTS_CONNECTION_STRING","value": "${{secrets.REDIS_CONNECTION_STRING}}","slotSetting": false}]'

      - name: Deploy resources to the prod Resource Group using a Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: OSS-prod
          template: ./bicep-template/template.bicep
          parameters: location="Australia East" sites_taa_portal_name="taa-portal-prod" serverfarms_as_taa_name="as-taa-prod"
          failOnStdErr: false
          deploymentMode: incremental
