# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - taa-portal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Lint
        uses: ricardochaves/python-lint@v1.4.0
        with:
#           python-root-list: "python_alelo tests"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--ignore=E201,E202,E501,F403,F405"
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
      
      - name: Perform spell check
        uses: sobolevn/misspell-fixer-action@0.1.0
        
      - name: Create a PR for any issues that are identified
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Fixes by misspell-fixer'
          title: 'Typos fix by misspell-fixer'

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.SP_CREDENTIALS }}
          
      - name: Run tests
        run: python manage.py test
        env:
          "Django__KeyVaultName": ${{ secrets.KEYVAULT_NAME }}
          
      - name: Calculate code coverage
        run: |
            coverage run --source="." --omit="adoptionsite/migrations*" manage.py test adoptionsite
            coverage report
        env:
            "Django__KeyVaultName": ${{ secrets.KEYVAULT_NAME }}
        
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.SP_CREDENTIALS}}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'taa-portal'
          slot-name: 'Production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0C5159A9530340D7AF08DBA9FC97E13F }}

      - name: Azure Setup Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'taa-portal'
          app-settings-json: '[{"name": "Django__KeyVaultName","value": "${{secrets.KEYVAULT_NAME }}","slotSetting": false},{"name": "Django__Debug","value": "True","slotSetting": false}]'
